<a href="https://colab.research.google.com/github/SMOKURsmoter/TensorFlow/blob/main/ch_01_Overview_of_TensorFlow_and_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Spis treści<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Sesja-TensorFlow" data-toc-modified-id="Sesja-TensorFlow-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Sesja TensorFlow</a></span></li><li><span><a href="#Stałe" data-toc-modified-id="Stałe-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Stałe</a></span></li><li><span><a href="#Operacje" data-toc-modified-id="Operacje-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Operacje</a></span></li><li><span><a href="#Węzły-zastępcze" data-toc-modified-id="Węzły zastępcze-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Węzły zastępcze</a></span></li><li><span><a href="#Tworzenie-tensorów-z-istniejących-obiektów" data-toc-modified-id="Tworzenie-tensorów-z-istniejących-obiektów-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Tworzenie tensorów z istniejących obiektów</a></span><ul class="toc-item"><li><span><a href="#Tensory-zerowego-rzędu-(skalary)" data-toc-modified-id="Tensory-zerowego-rzędu-(skalary)-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Tensory zerowego rzędu (skalary)</a></span></li><li><span><a href="#Tensory-1.-rzędu-(wektory)" data-toc-modified-id="Tensory-1.-rzędu-(wektory)-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Tensory 1. rzędu (wektory)</a></span></li><li><span><a href="#Tensory-2.-rzędu-(macierze)" data-toc-modified-id="Tensory-2.-rzędu-(macierze)-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Tensory 2. rzędu (macierze)</a></span></li><li><span><a href="#Tensory-3.-rzędu" data-toc-modified-id="Tensory-3.-rzędu-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Tensory 3. rzędu</a></span></li></ul></li><li><span><a href="#Zmienne" data-toc-modified-id="Zmienne-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Zmienne</a></span></li><li><span><a href="#Tworzenie-tensorów-z-funkcji-bibliotecznych" data-toc-modified-id="Tworzenie-tensorów-z-funkcji-bibliotecznych-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Tworzenie tensorów z funkcji bibliotecznych</a></span></li><li><span><a href="#Zamknięcie-sesji-interaktywnej" data-toc-modified-id="Zamknięcie-sesji-interaktywnej-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Zamknięcie sesji interaktywnej</a></span></li><li><span><a href="#Grafy-obliczeniowe" data-toc-modified-id="Grafy-obliczeniowe-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Grafy obliczeniowe</a></span><ul class="toc-item"><li><span><a href="#Budowa-i-uruchomienie-prostego-grafu-obliczeniowego" data-toc-modified-id="Budowa-i-uruchomienie-prostego-grafu-obliczeniowego-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Budowa i uruchomienie prostego grafu obliczeniowego</a></span></li><li><span><a href="#Graf-na-urządzeniach-obliczeniowych" data-toc-modified-id="Graf-na-urządzeniach-obliczeniowych-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Graf na urządzeniach obliczeniowych</a></span><ul class="toc-item"><li><span><a href="#Lista-dostępnych-urządzeń" data-toc-modified-id="Lista-dostępnych-urządzeń-9.2.1"><span class="toc-item-num">9.2.1&nbsp;&nbsp;</span>Lista dostępnych urządzeń</a></span></li><li><span><a href="#Domyślne-rozmieszczenie" data-toc-modified-id="Domyślne-rozmieszczenie-9.2.2"><span class="toc-item-num">9.2.2&nbsp;&nbsp;</span>Domyślne rozmieszczenie</a></span></li><li><span><a href="#Rozmieszczanie-na-CPU" data-toc-modified-id="Rozmieszczanie-na-CPU-9.2.3"><span class="toc-item-num">9.2.3&nbsp;&nbsp;</span>Rozmieszczanie na CPU</a></span></li><li><span><a href="#Rozmieszczanie-na-CPU-i-GPU" data-toc-modified-id="Rozmieszczanie-na-CPU-i-GPU-9.2.4"><span class="toc-item-num">9.2.4&nbsp;&nbsp;</span>Rozmieszczanie na CPU i GPU</a></span></li></ul></li><li><span><a href="#Wykonywanie-grafu-g-jako-domyślnego" data-toc-modified-id="Wykonywanie-grafu-g-jako-domyślnego-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Wykonywanie grafu g jako domyślnego</a></span></li></ul></li><li><span><a href="#Regresja-logistyczna-z-TensorFlow" data-toc-modified-id="Regresja-logistyczna-z-TensorFlow-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Regresja logistyczna z TensorFlow</a></span></li><li><span><a href="#Regresja-logistyczna-z-Keras" data-toc-modified-id="Regresja-logistyczna-z-Keras-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Regresja logistyczna z Keras</a></span></li></ul></div>

# TensorFlow 101 <a class="tocSkip">

In [ ]:
import tensorflow as tf
print('Wersja TensorFlow :',tf.__version__)
import numpy as np
print('Wersja Numpy :',np.__version__)
import sys
print('Interpreter Pythona i wersja:',sys.version)

Wersja TensorFlow : 1.10.0
Wersja Numpy : 1.15.0
Interpreter Pythona i wersja: 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0]


# Sesja TensorFlow

In [ ]:
tfs = tf.Session()

In [ ]:
hello = tf.constant("Witamy w projekcie TensorFlow!!")
print(tfs.run(hello))

b'Witamy w projekcie TensorFlow!!'


# Stałe

In [ ]:
const1 = tf.constant(34, name='x')
const2 = tf.constant(59.0, name='y')
const3 = tf.constant(32.0, dtype=tf.float32, name='z')
print('const1 (x): ', const1)
print('const2 (y): ', const2)
print('const3 (z): ', const3)

const1 (x):  Tensor("x:0", shape=(), dtype=int32)
const2 (y):  Tensor("y:0", shape=(), dtype=float32)
const3 (z):  Tensor("z:0", shape=(), dtype=float32)


In [ ]:
print('run([const1,const2,const3]) : ', tfs.run([const1, const2, const3]))

run([const1,const2,const3]) :  [34, 59.0, 32.0]


# Operacje

In [ ]:
op1 = tf.add(const2, const3)
op2 = tf.multiply(const2, const3)
print('op1 : ', op1)
print('op2 : ', op2)

op1 :  Tensor("Add:0", shape=(), dtype=float32)
op2 :  Tensor("Mul:0", shape=(), dtype=float32)


In [ ]:
print('run(op1) : ', tfs.run(op1))
print('run(op2) : ', tfs.run(op2))

run(op1) :  91.0
run(op2) :  1888.0


# Węzły zastępcze

In [ ]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print('p1 : ', p1)
print('p2 : ', p2)

p1 :  Tensor("Placeholder:0", dtype=float32)
p2 :  Tensor("Placeholder_1:0", dtype=float32)


In [ ]:
mult_op = p1 * p2  # skrót dla tf.multiply(p1, p2)

In [ ]:
print('run(mult_op,{p1:13.4, p2:61.7}) : ',tfs.run(mult_op,{p1:13.4, p2:61.7}))

run(mult_op,{p1:13.4, p2:61.7}) :  826.77997


In [ ]:
feed_dict={p1: 15.4, p2: 19.5}
print('run(mult_op,feed_dict = {p1:15.4, p2:19.5}) : ',
      tfs.run(mult_op, feed_dict=feed_dict))

run(mult_op,feed_dict = {p1:15.4, p2:19.5}) :  300.3


In [ ]:
feed_dict={p1: [2.0, 3.0, 4.0], p2: [3.0, 4.0, 5.0]}
print('run(mult_op,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}):',
      tfs.run(mult_op, feed_dict=feed_dict))

run(mult_op,feed_dict={p1:[2.0,3.0,4.0], p2:[3.0,4.0,5.0]}): [ 6. 12. 20.]


# Tworzenie tensorów z istniejących obiektów

## Tensory zerowego rzędu (skalary)

In [ ]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)

print('tf_t : ', tf_t)
print('run(tf_t) : \n', tfs.run(tf_t))

tf_t :  Tensor("Const_1:0", shape=(), dtype=float64)
run(tf_t) : 
 5.0


## Tensory 1. rzędu (wektory)

In [ ]:
a1dim = np.array([1, 2, 3, 4, 5.99])
print('Kształt a1dim : ', a1dim.shape)

tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0] : ', tf_t[0])
print('tf_t[0] : ', tf_t[2])
print('run(tf_t) : \n', tfs.run(tf_t))

Kształt a1dim :  (5,)
tf_t :  Tensor("Const_2:0", shape=(5,), dtype=float64)
tf_t[0] :  Tensor("strided_slice:0", shape=(), dtype=float64)
tf_t[0] :  Tensor("strided_slice_1:0", shape=(), dtype=float64)
run(tf_t) : 
 [1.   2.   3.   4.   5.99]


## Tensory 2. rzędu (macierze)

In [ ]:
a2dim = np.array([(1, 2, 3, 4, 5.99),
                  (2, 3, 4, 5, 6.99),
                  (3, 4, 5, 6, 7.99)
                  ])
print('Kształt a2dim : ', a2dim.shape)

tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0] : ', tf_t[0][0])
print('tf_t[1][2] : ', tf_t[1][2])
print('run(tf_t) : \n', tfs.run(tf_t))

Kształt a2dim :  (3, 5)
tf_t :  Tensor("Const_3:0", shape=(3, 5), dtype=float64)
tf_t[0][0] :  Tensor("strided_slice_3:0", shape=(), dtype=float64)
tf_t[1][2] :  Tensor("strided_slice_5:0", shape=(), dtype=float64)
run(tf_t) : 
 [[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]]


## Tensory 3. rzędu

In [ ]:
a3dim = np.array([[[1, 2],
                   [3, 4]
                   ],
                  [[5, 6],
                   [7, 8]
                   ]
                  ])
print('Kształt a3dim : ', a3dim.shape)

tf_t = tf.convert_to_tensor(a3dim, dtype=tf.float64)

print('tf_t : ', tf_t)
print('tf_t[0][0][0] : ', tf_t[0][0][0])
print('tf_t[1][1][1] : ', tf_t[1][1][1])
print('run(tf_t) : \n', tfs.run(tf_t))

Kształt a3dim :  (2, 2, 2)
tf_t :  Tensor("Const_4:0", shape=(2, 2, 2), dtype=float64)
tf_t[0][0][0] :  Tensor("strided_slice_8:0", shape=(), dtype=float64)
tf_t[1][1][1] :  Tensor("strided_slice_11:0", shape=(), dtype=float64)
run(tf_t) : 
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


# Zmienne

In [ ]:
# Model liniowy y = w * x + b
# Definiowanie parametrów modelu
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Definiowanie wejścia i wyjścia modelu
x = tf.placeholder(tf.float32)
y = w * x + b

print('w:', w)
print('x:', x)
print('b:', b)
print('y:', y)

w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
x: Tensor("Placeholder_2:0", dtype=float32)
b: <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>
y: Tensor("add_1:0", dtype=float32)


In [ ]:
# Inicjacja i wydruk zmiennej y
tfs.run(tf.global_variables_initializer())
print('run(y,{x:[1,2,3,4]}) : ', tfs.run(y, {x: [1, 2, 3, 4]}))

run(y,{x:[1,2,3,4]}) :  [0.         0.3        0.6        0.90000004]


# Tworzenie tensorów z funkcji bibliotecznych

In [ ]:
a = tf.zeros((100,))
print(tfs.run(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


# Zamknięcie sesji interaktywnej

In [ ]:
tfs.close()

# Grafy obliczeniowe

## Budowa i uruchomienie prostego grafu obliczeniowego

In [ ]:
# Przyjmujemy model liniowy y = w * x + b
# Definiowanie parametrów modelu
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Definiowanie wejścia i wyjścia modelu
x = tf.placeholder(tf.float32)
y = w * x + b
output = 0

with tf.Session() as tfs:
    # Inicjacja i wydruk zmiennej y
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})
print('wyjście : ', output)

output :  [0.         0.3        0.6        0.90000004]


## Graf na urządzeniach obliczeniowych

### Lista dostępnych urządzeń

In [ ]:
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17276089553867621096
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 14855356416
locality {
  bus_id: 1
  links {
  }
}
incarnation: 5054245287873480849
physical_device_desc: "device: 0, name: Quadro P5000, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


### Domyślne rozmieszczenie

In [ ]:
tf.reset_default_graph()

# Definiowanie parametrów modelu
w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
# Definiowanie wejścia i wyjścia modelu
x = tf.placeholder(name='x', dtype=tf.float32)
y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # inicjacja i wydruk zmiennej y
    tfs.run(tf.global_variables_initializer())
    print('wyjście', tfs.run(y, {x: [1, 2, 3, 4]}))

output [0.         0.3        0.6        0.90000004]


### Rozmieszczanie na CPU

In [ ]:
tf.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Definiowanie parametrów modelu
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    # Definiowanie wejścia i wyjścia modelu
    x = tf.placeholder(name='x', dtype=tf.float32)
    y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # Inicjacja i wydruk zmiennej y
    tfs.run(tf.global_variables_initializer())
    print('wyjście', tfs.run(y, {x: [1, 2, 3, 4]}))

output [0.         0.3        0.6        0.90000004]


### Rozmieszczanie na CPU i GPU

In [ ]:
tf.reset_default_graph()

with tf.device('/device:CPU:0'):
    # Definiowanie parametrów modelu
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    # Definiowanie wejścia i wyjścia modelu
    x = tf.placeholder(name='x', dtype=tf.float32)
with tf.device('/device:GPU:0'):
    y = w * x + b

config = tf.ConfigProto()
config.log_device_placement = True

with tf.Session(config=config) as tfs:
    # inicjacja i wydruk zmiennej y
    tfs.run(tf.global_variables_initializer())
    print('wyjście', tfs.run(y, {x: [1, 2, 3, 4]}))

## Wykonywanie grafu g jako domyślnego

In [ ]:
g = tf.Graph()
output = 0

# Przyjmujemy model liniowy y = w * x + b

with g.as_default():
    # Definiowanie parametrów modelu
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    # Definiowanie wejścia i wyjścia modelu
    x = tf.placeholder(tf.float32)
    y = w * x + b

with tf.Session(graph=g) as tfs:
    # Inicjacja i wydruk zmiennej y
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1, 2, 3, 4]})

print('wyjście : ', output)

# Regresja logistyczna z TensorFlow

In [ ]:
# Wczytywanie dslib
DSLIB_HOME = '../datasetslib'
import sys
if not DSLIB_HOME in sys.path:
    sys.path.append(DSLIB_HOME)
%reload_ext autoreload
%autoreload 2
import datasetslib as dslib

# Ustaw katalog główny dla zbiorów danych przed importem datasetslib
import os
dslib.dsroot = os.path.join(os.path.expanduser('~'),'datasets')

from datasetslib.utils import imutil
from datasetslib.utils import nputil
from datasetslib.mnist import MNIST

In [ ]:
mnist=MNIST()

# Przygotuj dane x i y

x_train,y_train,x_test,y_test=mnist.load_data()

mnist.y_onehot = True
mnist.x_layout = imutil.LAYOUT_NP
x_test = mnist.load_images(x_test)
y_test = nputil.onehot(y_test)

print('Wczytane x i y')
print('Szkolenie: x:{}, y:{}'.format(len(x_train),y_train.shape))
print('Test: x:{}, y:{}'.format(x_test.shape,y_test.shape))

In [ ]:
# Definiowanie hiperparametrów
learning_rate = 0.001
n_epochs = 5
mnist.batch_size = 100


# Zresetuj graf, jeśli ponownie uruchamiasz tę komórkę
tf.reset_default_graph()

# Zdefiniowanie obrazów wejściowych
x = tf.placeholder(dtype=tf.float32, shape=[None, mnist.n_features])
# Zdefiniowanie etykiet wyjściowych
y = tf.placeholder(dtype=tf.float32, shape=[None, mnist.n_classes])

# Parametry modelu
w = tf.Variable(tf.zeros([mnist.n_features, mnist.n_classes]))
b = tf.Variable(tf.zeros([mnist.n_classes]))

# Sam model
logits = tf.add(tf.matmul(x, w), b)
y_hat = tf.nn.softmax(logits)

# Definiowanie funkcji straty dla szkolenia
epsilon = tf.keras.backend.epsilon()
y_hat_clipped = tf.clip_by_value(y_hat, epsilon, 1 - epsilon)
y_hat_log = tf.log(y_hat_clipped)
cross_entropy = -tf.reduce_sum(y * y_hat_log, axis=1)
loss_f = tf.reduce_mean(cross_entropy)

optimizer = tf.train.GradientDescentOptimizer
optimizer_f = optimizer(learning_rate=learning_rate).minimize(loss_f)

# Definiowanie funkcji dokładności dla testu
predictions_check = tf.equal(tf.argmax(y_hat, 1), tf.argmax(y, 1))
accuracy_f = tf.reduce_mean(tf.cast(predictions_check, tf.float32))

# Szkolenie i test
n_batches = int(60000/mnist.batch_size)

with tf.Session() as tfs:
    tf.global_variables_initializer().run()
    for epoch in range(n_epochs):
        mnist.reset_index()
        for batch in range(n_batches):
            x_batch, y_batch = mnist.next_batch()
            feed_dict={x: x_batch, y: y_batch}
            batch_loss,_ = tfs.run([loss_f, optimizer_f],feed_dict=feed_dict )
            #print('Strata dla grupy:{}'.format(batch_loss))

        feed_dict = {x: x_test, y: y_test}
        accuracy_score = tfs.run(accuracy_f, feed_dict=feed_dict)
        print('epoka {0:04d}  dokładność={1:.8f}'
              .format(epoch, accuracy_score))

# Regresja logistyczna z Keras

In [ ]:
x_train_im = mnist.load_images(x_train)

x_train_im, x_test_im = x_train_im / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='sgd',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train_im, y_train, epochs=5)
model.evaluate(x_test_im, nputil.argmax(y_test))